name: test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build ccompress
        run: |
          std=c23; cc -std=$std -E -x c /dev/null -o /dev/null 2>/dev/null || std=c2x
          cc -Wall -Wextra -pedantic -std=$std -O2 -D_POSIX_C_SOURCE=200809L -lpthread -o ccompress compress.c
      - name: Run tests
        run: |
          make test
          ./test/run.sh
  linux-musl:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v7
      - name: Install deps
        run: apk add --no-cache gcc musl-dev make
      - name: Build and test
        run: |
          std=c23; cc -std=$std -E -x c /dev/null -o /dev/null 2>/dev/null || std=c2x
          cc -Wall -Wextra -pedantic -std=$std -O2 -D_POSIX_C_SOURCE=200809L -lpthread -o ccompress compress.c
          make test
          ./test/run.sh

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build and test
        run: |
          std=c23; cc -std=$std -E -x c /dev/null -o /dev/null 2>/dev/null || std=c2x
          cc -Wall -Wextra -pedantic -std=$std -O2 -D_POSIX_C_SOURCE=200809L -lpthread -o ccompress compress.c
          make test
          ./test/run.sh

  mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v7
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc make diffutils
      - name: Build and test
        run: |
          std=c23; gcc -std=$std -E -x c /dev/null -o /dev/null 2>/dev/null || std=c2x
          gcc -Wall -Wextra -pedantic -std=$std -O2 -D_POSIX_C_SOURCE=200809L -lpthread -o ccompress compress.c
          make test
          ./test/run.sh

  msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      - name: Install make
        run: choco install make -y --no-progress
      - name: Build ccompress with MSVC
        run: make CC=cl CFLAGS="/std:c17 /O2" LDFLAGS="" STD=
      - name: Run test suite (PowerShell)
        run: pwsh ./test/run.ps1
